// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmAATuX4irQsIEAVDU9VzhelD_9Oc9pk',
    appId: '1:930686966530:web:cf82a19bb85b6e8f28801b',
    messagingSenderId: '930686966530',
    projectId: 'lp-flutter-shop',
    authDomain: 'lp-flutter-shop.firebaseapp.com',
    storageBucket: 'lp-flutter-shop.appspot.com',
    measurementId: 'G-GC6VDKE2D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcHSRYH0NNI2Ja4-jxbwkva8kLVnBp2AE',
    appId: '1:930686966530:android:1e424bc8b8f6bcc728801b',
    messagingSenderId: '930686966530',
    projectId: 'lp-flutter-shop',
    storageBucket: 'lp-flutter-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfLvWOTU6OU7IkncbIK1ZAJOSjZPMnTzY',
    appId: '1:930686966530:ios:35e1612c4e486a8728801b',
    messagingSenderId: '930686966530',
    projectId: 'lp-flutter-shop',
    storageBucket: 'lp-flutter-shop.appspot.com',
    iosClientId: '930686966530-ltt30o6cdpgf8h9449eopag6vcag0h7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSweaterShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfLvWOTU6OU7IkncbIK1ZAJOSjZPMnTzY',
    appId: '1:930686966530:ios:35e1612c4e486a8728801b',
    messagingSenderId: '930686966530',
    projectId: 'lp-flutter-shop',
    storageBucket: 'lp-flutter-shop.appspot.com',
    iosClientId: '930686966530-ltt30o6cdpgf8h9449eopag6vcag0h7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSweaterShop',
  );
}
